# Generated by Django 4.0.6 on 2022-07-12 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category name')),
            ],
            options={
                'verbose_name': 'HomeCategory',
                'verbose_name_plural': 'HomeCategories',
            },
        ),
        migrations.CreateModel(
            name='HomeSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='SubCategory name')),
                ('homecategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcateg', to='main.homecategory')),
            ],
            options={
                'verbose_name': 'HomeSubCategory',
                'verbose_name_plural': 'HomeSubCategories',
            },
        ),
    ]
