# Generated by Django 4.0.6 on 2022-07-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_homecategory_homesubcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeFeatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=20, verbose_name='Item price')),
                ('about', models.TextField(verbose_name='Item about')),
                ('img', models.ImageField(upload_to='media', verbose_name='Item image')),
            ],
            options={
                'verbose_name': 'HomeFeatureItem',
                'verbose_name_plural': 'HomeFeatureItems',
            },
        ),
    ]
