# Generated by Django 4.0.6 on 2022-07-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_homefeatureitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Brand name')),
            ],
            options={
                'verbose_name': 'HomeBrand',
                'verbose_name_plural': 'HomeBrands',
            },
        ),
    ]
