# Generated by Django 4.0.6 on 2022-07-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_homebrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebrand',
            name='count',
            field=models.IntegerField(null=True, verbose_name='Brand count'),
        ),
    ]
