# Generated by Django 4.0.6 on 2022-07-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_homeshipping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeshipping',
            options={'verbose_name': 'HomeShipping', 'verbose_name_plural': 'HomeShippings'},
        ),
        migrations.AddField(
            model_name='homeshipping',
            name='name',
            field=models.CharField(blank=True, max_length=10, verbose_name='HomeShipping name'),
        ),
    ]
